version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: mse_stock_data
      POSTGRES_USER: dians
      POSTGRES_PASSWORD: dians123
    volumes:
      - postgres_mse_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dians -d mse_stock_data"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mse_stock_data
      DB_USER: dians
      DB_PASSWORD: dians123
    volumes:
      - .:/app
    command: >
      sh -c "python StartApp.py"

volumes:
  postgres_mse_data: