name: Linting Checks
on:
  pull_request:
    types:
      - opened
  push:
    branches: [ main, cicd ]

jobs:
  linting:
    name: Run Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ===== Frontend (React + TypeScript) =====
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run ESLint (TypeScript)
        working-directory: ./frontend
        run: npx eslint src/