name: Linting Checks
on:
  pull_request:
    types:
      - opened
  push:
    branches: [ main, cicd ]

jobs:
  linting:
    name: Run Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ===== Frontend (React + TypeScript) =====
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run ESLint (TypeScript)
        working-directory: ./frontend
        run: npx eslint src/

      # ===== Backend (SpringBoot/Java) =====
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Checkstyle (Java)
        working-directory: ./DesignAndArchitectureProject
        run: mvn checkstyle:check

      # ===== Python (Scraper) =====
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python linters
        run: |
          python -m pip install --upgrade pip
          pip install flake8 bandit

      - name: Run Flake8 (Python style)
        working-directory: ./ScrapingService
        run: flake8 . --count --show-source --statistics

      - name: Run Bandit (Python security)
        working-directory: ./ScrapingService
        run: bandit -r . -ll