name: SonarCloud Scan
on:
  push:
    branches: [ main, cicd ]
  pull_request:
    branches: [ main ]

jobs:
  sonarcloud-scan:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: dians
          POSTGRES_PASSWORD: dians123
          POSTGRES_DB: mse_stock_data
        ports:
          - 5433:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # --- Backend (SpringBoot - Java) Analysis ---
      - name: Set up JDK 17 for SpringBoot
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        working-directory: ./DesignAndArchitectureProject
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=KIII-DAS-Project

      # --- Frontend (React - JavaScript) Analysis ---
      - name: Set up Node.js for React
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install React dependencies
        working-directory: ./frontend
        run: npm install

      # --- Python (Web Scraper) Analysis ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # --- Run SonarCloud Scan (Multi-language) ---
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}